# Site settings
title: Traffic Hackers - Blog
email: andrew@acollier.com
description:
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://traffichackers.com" # the base hostname & protocol for your site
twitter_username: traffichackers
github_username:  traffichackers

# Build settings
markdown: kramdown
